- name: Configure App
  hosts: reddit-app
  become: true
  
  tasks:
    - name: Get DB IP
      set_fact:
         mongo_bind_ip: "{{groups['reddit-db'][0]}}"

    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/appuser/db_config
        owner: appuser
        group: appuser
      notify: reload puma

    - name: enable puma
      systemd: name=puma enabled=yes

  handlers:
  - name: reload puma
    systemd: name=puma state=restarted
