---
- hosts: all
  gather_facts: yes
  become: yes

  vars:
      mongo_bind_ip: 192.168.205.143

  tasks:
    - name: Add mongo repo key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: EA312927
        state: present

    - name: Appent repository
      apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present

    - name: install mongo
      apt:
        name: mongodb
        state: present

  handlers:
    - name: restart mongo
      systemd: name=mongodb state=restarted
