---
- hosts: reddit-db
  gather_facts: yes
  become: yes

  vars:
      mongo_bind_ip: 0.0.0.0
  tasks:
    - name: Add mongo repo key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: EA312927
        state: present

    - name: Appent repository
      apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present
          
    - name: install mongo
      apt:
        name: mongodb
        state: present

    - name: Change mongo config file
      become: true
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongodb.conf
        mode: 0644
      notify: restart mongo

  handlers:
    - name: restart mongo
      systemd: name=mongodb state=restarted
